name: Continuous Integration

on:
  push:
    branches:
    - gh-2331-github-actions
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        test-type:
        - unit-test
        - integration-test
        modules:
        - :gaffer2,:core,:access,:cache,:common-util,:data,:exception,:graph,:operation,:serialisation,:store,:type
        #- :accumulo-store,:accumulo-rest # commented out for development as they take a while
        #- :hbase-store,:hbase-rest
        - :parquet-store,:parquet-rest
        - :integration-test,:federated-store,:map-store,:map-rest
        - :rest-api,:core-rest,:store-implementation,:proxy-store,:example,:basic,:basic-model,:basic-rest,:road-traffic,:road-traffic-model,:road-traffic-generators,:road-traffic-rest,:road-traffic-demo,:federated-demo
        - :flink-library,:hdfs-library,:spark,:spark-library,:spark-accumulo-library
        - :library,:time-library
        - :cache-library,:sketches-library,:bitmap-library,:hazelcast-cache-service,:jcs-cache-service

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install
      run: mvn clean install -P quick,coverage -pl ${{matrix.modules}} -am
    - name: Test
      run: mvn test -P${{matrix.test-type}} -pl ${{matrix.modules}}
    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      with:
        verbose: true
