name: Continuous Integration

on: [ pull_request ]

jobs:
  check-all-modules-are-tested:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check all modules are tested
      run: ./cd/check_modules.sh

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        modules:
        - :gaffer2,:core,:access,:cache,:common-util,:data,:exception,:graph,:operation,:serialisation,:store,:type
        - :accumulo-store,:accumulo-rest
        - :hbase-store,:hbase-rest
        - :parquet-store,:parquet-rest
        - :integration-test,:federated-store,:map-store,:map-rest
        - :rest-api,:core-rest,:store-implementation,:proxy-store,:example,:basic,:basic-model,:basic-rest,:road-traffic,:road-traffic-model,:road-traffic-generators,:road-traffic-rest,:road-traffic-demo,:federated-demo
        - :flink-library,:hdfs-library,:spark,:spark-library,:spark-accumulo-library
        - :library,:time-library
        - :cache-library,:sketches-library,:bitmap-library,:hazelcast-cache-service,:jcs-cache-service

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install
      run: mvn clean -q install -P quick -pl ${{matrix.modules}} -am

    - name: Test
      run: mvn verify -q -P coverage -pl ${{matrix.modules}}

    - name: Upload Coverage
      uses: codecov/codecov-action@v1

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path:
          ~/.m2/repository
          !~/.m2/repository/uk

